### ISSUE TITLE
How to run this model on multiple gpu？

### ISSUE THREAD

**Issue by hmppt** [zhuhao-nju/mofanerf#11]
Hello, dear author of mofanerf: 
I want to use your data set to retrain a model of my own, so I downloaded the mofanerf dataset, after adjusting the chunk and netchunk and N-rand to the recommended minimum, I found that I still need to train 5000 hours on a single GPU3090 . I want to perform multi-card parallel training, but the model is created by the **creat_nerf()** and returns a value directly. This is different from the code I have seen before, and I don't know how to process the data in parallel. How can I use multi-card for training?

**Comment by yiyuzhuang** [comment]
Hello! I am pleased to inform you that we have successfully implemented multi-card training. To enable the use of multiple GPUs, please modify Line 12 of the 'run_train.py' file. Specifically, you can replace "os.environ['CUDA_VISIBLE_DEVICES'] = '0'" with "os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3'" to support the use of GPUs 0, 1, 2, and 3.
