### ISSUE TITLE
Wierd images result 

### ISSUE THREAD

**Issue by yumikim381** [zhuhao-nju/mofanerf#14]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/102374351/229193490-ca67d368-2cb9-40f6-9536-1ad709e3367a.png">

Even after following the suggestions from this issue(https://github.com/zhuhao-nju/mofanerf/issues/6#issue-1268283928) and running the pretrained_model_download , and getting the exact same error as @atuyoti, i still get the above images. 

Does anyone also run into these issues? Am i missing something? 

How does it look when it's correctly run?

**Comment by Net-Maker** [comment]
same issue.
have you finished it ?
