### ISSUE TITLE
Fit into multiple images

### ISSUE THREAD

**Issue by apple2373** [zhuhao-nju/mofanerf#2]
Hi,

Thank you for sharing the code! Is it possible to fit the pretrained model into multiple images? The current demo fit the model into a single image of a face, but I have multiple views of the same person, and want to fit the model to them.

**Comment by yiyuzhuang** [comment]
Sure, a potential solution is to optimize for each image in turns inside each optimizing iteration. You may modify "run_fit.py" to achieve it, and I supposed more iterations are required.
