### ISSUE TITLE
How to color the color the raw scanned models?

### ISSUE THREAD

**Issue by eckertzhang** [zhuhao-nju/mofanerf#3]
Thanks for your good work.
In the paper, you said 'we use the multi-view images to color the raw scanned models', could you share which method you adopt to color the raw sccanned models?

**Comment by zhuhao-nju** [comment]
Hi, 

We inverse-project the multi-view images to each triangle face on the raw scanned mesh, transferring the pixels from the images to the triangle faces, then blend them to build a texture atlas. The pixels that are occluded or with a normal direction perpendicular to the camera direction are filtered out. The blending process is to simply compute the mean of pixels.

By the way, the re-rendered images for training can be downloaded from https://facescape.nju.edu.cn/ now.

**Comment by eckertzhang** [comment]
@zhuhao-nju Thanks for your reply!
