### ISSUE TITLE
Image is not rendered correctly

### ISSUE THREAD

**Issue by atuyoti** [zhuhao-nju/mofanerf#6]
In the "Fit to the processed image" Step, I use ./data/fit/segRelRes/1.png as a target image. As a result of 2000 epoch, The image was generated. Is it correct??
![segRelRes_1_2000](https://user-images.githubusercontent.com/29838823/173190853-44caf788-c045-483c-a7de-ddab21480c60.png)

In addition, In the "Render images of novel views" Step, The image was generated.

![fitRes_0](https://user-images.githubusercontent.com/29838823/173190980-8e3ab25a-d91d-4fbe-a0b0-c45134ff386f.png)

What kind of causes can you think of?

Environment:
CPU: Intel core i7
GPU: RTX 3060, 12GB
RAM: 16GB

PyTorch 1.9.0
dlib 19.24.0
matplotlib 3.5.2
numpy 1.21.6
imageio 2.19.3
imageio-ffmpeg 0.4.7

**Comment by trifle** [comment]
@atuyoti You didn't download the pre-trained model. Run the download script first.

**Comment by atuyoti** [comment]
@trifle 
Sorry, I make mistake in the download script.
After your comment, the download was successful.
> bash ./download_pretrained_models.sh
pretrained_models.tar.gz has already been downloaded.
pretrained models have been extracted to ./logs/

Bat in the Fit to the processed image process, There was an error associated with the unzip file of pretrained_models.tar.gz.

> D:\mofanerf>python run_fit.py --filePath ./data/fit/segRelRes/1.png
1
Found ckpts ['./logs\\mofanerf_0to300\\300000.tar']
Reloading from ./logs\mofanerf_0to300\300000.tar
Traceback (most recent call last):
  File "run_fit.py", line 449, in <module>
    is_load_par=args.is_load_par, args=args)
  File "run_fit.py", line 160, in train
    render_kwargs_train, render_kwargs_test, start, grad_vars, optimizer, logger, render = create_nerf(args)
  File "D:\mofanerf\tools\create_model_condition.py", line 89, in create_nerf
    start = int(ckpt_path.split("/")[-1][:-4])
ValueError: invalid literal for int() with base 10: 'logs\\mofanerf_0to300\\300000'

**Comment by trifle** [comment]
Cool! Happy to hear it’s fixed now.

**Comment by atuyoti** [comment]
@trifle 
Sorry for the numerous comments.
After download,  There was an error associated with the unzip file of pretrained_models.tar.gz in the Fit to the processed image process.

> D:\mofanerf>python run_fit.py --filePath ./data/fit/segRelRes/1.png
1
Found ckpts ['./logs\mofanerf_0to300\300000.tar']
Reloading from ./logs\mofanerf_0to300\300000.tar
Traceback (most recent call last):
File "run_fit.py", line 449, in
is_load_par=args.is_load_par, args=args)
File "run_fit.py", line 160, in train
render_kwargs_train, render_kwargs_test, start, grad_vars, optimizer, logger, render = create_nerf(args)
File "D:\mofanerf\tools\create_model_condition.py", line 89, in create_nerf
start = int(ckpt_path.split("/")[-1][:-4])
ValueError: invalid literal for int() with base 10: 'logs\mofanerf_0to300\300000'

**Comment by trifle** [comment]
Hi @atuyoti 
sure, don't worry. It's not my repository so I may be wrong, but it seems that the code assumes a Linux/Unix/MacOS filesystem.

It splits the path by the forward slash ("/"), but on windows, it's the backwards slash ("\"). Maybe you can fix it in the code or try on a linux machine.

**Comment by atuyoti** [comment]
@trifle 
Thank you for the advice.
Everything went well!

**Comment by trifle** [comment]
@atuyoti Wonderful, congratulations!
