### ISSUE TITLE
expression derived from FaceScape?

### ISSUE THREAD

**Issue by tomguluson92** [zhuhao-nju/mofanerf#7]
Dear author,   
         As mentioned in the `mofanerf` paper, **appearance** & **shape** both derive from FaceScape. I wonder if the
**expression** comes from FaceScape or not. 
         Really eager for the kindness help, thank you.

**Comment by yiyuzhuang** [comment]
Hi @tomguluson92,

The expression codes are a list of latent codes optimized during training, instead of obtrained from FaceScape. 
It was shown that the choice of latent codes led to better results in our ablation study.
