### ISSUE TITLE
RE latent codes for animation

### ISSUE THREAD

**Issue by arlorostirolla** [zhuhao-nju/mofanerf#8]
Hello,
Your project looks very effective! 
I was wondering how i could go about animating a mofanerf model via video, say of someone talking?
My intuition  would be to run the model on each frame and determine the latent representation, and then interpolate through them to generate the video. 

To be specific, i'm trying to do something like this (See 1.28)
https://youtu.be/Al6NTbgka1o?t=88

Do you have any advice on doing this?

**Comment by yiyuzhuang** [comment]
Hi @arloporter ,

It can be achieved with our fitting code [run_fit.py](https://github.com/zhuhao-nju/mofanerf/blob/main/run_fit.py), but empirically, the large view-angle and the uneven lighting may degrade the performance, and the artifacts may be synthesized in the mouth region.  I think further optimization is still required to animate a high-quality talking face.
